export enum COMPONENTSNAME {
  HOME = 'Home',
  BOOKSHELF = 'Bookshelf',
  PEOPLE = 'People',
  BOTTOM_TAB = 'BottomTab',
  GENERATE_STORY = 'GenerateStory',
  STORY_TELLING = 'StoryTelling',
  STORY = 'Story',
  ACTIVITIES = 'Activities',
  SELECT_PLAYER = 'SelectPlayer',
  QUESTIONS = 'Questions',
  SELECT_LANGUAGE = 'SelectLanguage',
  SIGN_UP = 'SignUp',
  SIGN_IN = 'SignIn',
  TERMS_AND_CONDITIONS = 'TermsAndConditions',
  HELP_CENTER = 'HelpCenter',
  ACCOUNT = 'Account',
}
