export enum SCREEN_NAME {
  HOME = 'Home',
  BOOKSHELF = 'Bookshelf',
  PEOPLE = 'People',
  BOTTOM_TAB = 'BottomTab',
  GENERATE_STORY = 'GenerateStory',
  STORY_TELLING = 'StoryTelling',
  STORY = 'Story',
  ACTIVITIES = 'Activities',
  SELECT_PLAYER = 'SelectPlayer',
  QUESTIONS = 'Questions',
  SELECT_LANGUAGE = 'SelectLanguage',
  SIGN_UP = 'SignUp',
  SIGN_IN = 'SignIn',
  TERMS_AND_CONDITIONS = 'TermsAndConditions',
  HELP_CENTER = 'HelpCenter',
  ACCOUNT = 'Account',
  SPLASH_SCREEN = 'SplashScreen',
  ONBOARDING = 'Onboarding',
  SOCIAL_SIGN_IN = 'SocialSignIn',
  CREATE_CHILD_PROFILE = 'CreateChildProfile',
  PROFILE_SETTINGS = 'ProfileSettings',
  CHANGE_PASSWORD = 'ChangePassword',
  ABOUT_APP = 'AboutApp',
}
